package jo.app;

import java.util.Set;

import com.google.common.collect.ImmutableSet;

public class MarketRecorderStocks {
    // http://etfdb.com/compare/volume/
    public static final Set<String> TICKS_ONLY_ETFS = ImmutableSet.of(
            "SPY",
            "SQQQ",
            //"TQQQ",
            //"QQQ",
            "EEM",
            "XLF",
            "VXX",
            "UVXY",
            "GDX",
            "TVIX",
            "EFA",
            "IWM",
            "FXI",
            "UWTI",
            "USO",
            "XLU",
            "AMLP",
            "EWZ",
            "XOP",
            "JNK",
            "SVXY",
            "HYG",
            "XLE",
            "VWO",
            "XLK",
            "XLP",
            "XLI",
            "SPXU",
            "GDXJ",
            "JNUG",
            "IAU",
            "IEMG",
            "EWJ",
            "VEA",
            "TZA",
            "TLT",
            "XLV",
            "IEFA",
            "LABD",
            "OIH",
            "RSX",
            "IYR",
            "EZU",
            "SLV",
            "GLD",
            "DGAZ",
            "LQD",
            "XLB",
            "SDS",
            "NUGT",
            "VNQ",
            "XLY",
            "DIA",
            "KRE",
            "QID",
            "XRT",
            "EWT",
            "IVV",
            "EWH",
            "SPXL",
            "SH",
            "DWT",
            "SMH",
            "DUST");

    // SPY holdings
    public static final Set<String> TICKS_ONLY_STOCKS = ImmutableSet.of(
            // "AAPL",
            "MSFT",
            "AMZN",
            "FB",
            "JPM",
            "JNJ",
            "GOOG",
            //"GOOGL",
            "XOM",
            "BAC",
            "WFC",
            "INTC",
            "T",
            "V",
            "UNH",
            "CVX",
            "PFE",
            "CSCO",
            "HD",
            "VZ",
            "PG",
            "C",
            "BA",
            "ABBV",
            "MA",
            "KO",
            "CMCSA",
            "PM",
            "ORCL",
            "PEP",
            "DWDP",
            "DIS",
            "MRK",
            "NVDA",
            "MMM",
            "NFLX",
            "IBM",
            "WMT",
            "MCD",
            "GE",
            "AMGN",
            "MO",
            "HON",
            "ADBE",
            "MDT",
            "ABT",
            "BMY",
            "UNP",
            "TXN");
}
